### ISSUE TITLE
missing eslint-plugin-svelte3 depenedency

### ISSUE THREAD

**Issue by alexbjorlig** [tonyketcham/sapper-tailwind2-template#11]
Should eslint-plugin-svelte3 not be part of the package.json?

**Comment by tonyketcham** [comment]
Thanks @alexbjorlig you're right, it totally should be. I had ESLint set up in a general sense but it can be improved on the TS Svelte-specific end

**Comment by alexbjorlig** [comment]
I hoped this repo would be the solution for getting eslint+tsc+sapper working 😅 I hope that is something sveltekit will fix

**Comment by tonyketcham** [comment]
Yeah, the Svelte/Sapper ecosystem is currently too segmented and changing as far as hooking everything up goes versus that of Vue/Nuxt or React/Next where everything typically just works. As the community matures and SvelteKit comes out, that problem will likely be addressed.

But hang on and don't abandon this project! We'll get ESLint fully configured

**Comment by tonyketcham** [comment]
@alexbjorlig I've added Svelte-specific config for eslint. Let me know if there are any tweaks to my config that you'd like to propose!
