### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by dok42** [tonyketcham/sapper-tailwind2-template#155]
Hi, does it change something if I don't use Typescript? 
Have I to edit some config files ? 
Also, I do not use yarn, but npm (pnpm).. could this raise issues ?

Thank you very much for this template.

**Comment by tonyketcham** [comment]
Big apologies for a late reply on this - 

You can use normal Javascript by deleting the `lang="ts"` attribute on script tags and it should work as expected.

Yarn/npm will both work fine as well!
